// src/App.tsx
import React, { useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { Check } from 'lucide-react';
import { Customer, adaptCustomer } from './types';
import { checkWaiverStatus, searchCustomers, logCheckIn } from './api';

import { SearchBar } from './SearchBar';
import { CustomerList } from './CustomerList';
import { CustomerDetail } from './CustomerDetail';

// Define the Redux state type
export interface RootState {
  customers: Customer[];
  isLoading: boolean;
  error: string | null;
  selectedCustomer: Customer | null;
  guestCount: number;
  showWaiver: boolean;
  showConfirmation: boolean;
  searchQuery: string;
  searchType: 'email' | 'phone' | 'lot';
}

// Action creators
const setCustomers = (customers: Customer[]) => ({ type: 'SET_CUSTOMERS', payload: customers });
const setLoading = (isLoading: boolean) => ({ type: 'SET_LOADING', payload: isLoading });
const setError = (error: string | null) => ({ type: 'SET_ERROR', payload: error });
const setSelectedCustomer = (customer: Customer | null) => ({ type: 'SET_SELECTED_CUSTOMER', payload: customer });
const setGuestCount = (count: number) => ({ type: 'SET_GUEST_COUNT', payload: count });
const setShowWaiver = (show: boolean) => ({ type: 'SET_SHOW_WAIVER', payload: show });
const setShowConfirmation = (show: boolean) => ({ type: 'SET_SHOW_CONFIRMATION', payload: show });
const setSearchQuery = (query: string) => ({ type: 'SET_SEARCH_QUERY', payload: query });
const resetState = () => ({ type: 'RESET_STATE' });

function App() {
  const dispatch = useDispatch();
  const customers = useSelector((state: RootState) => state.customers);
  const isLoading = useSelector((state: RootState) => state.isLoading);
  const error = useSelector((state: RootState) => state.error);
  const selectedCustomer = useSelector((state: RootState) => state.selectedCustomer);
  const guestCount = useSelector((state: RootState) => state.guestCount);
  const showConfirmation = useSelector((state: RootState) => state.showConfirmation);
  const searchQuery = useSelector((state: RootState) => state.searchQuery);

  const USE_MOCK_API = import.meta.env.VITE_USE_MOCK_API === 'true';

  // Add useEffect to handle auto-dismiss of confirmation banner
  useEffect(() => {
    let timer: NodeJS.Timeout;
    if (showConfirmation) {
      timer = setTimeout(() => {
        dispatch(resetState());
      }, 3000);
    }
    return () => {
      if (timer) clearTimeout(timer);
    };
  }, [showConfirmation, dispatch]);

  const handleSearch = async (query: string, type: 'email' | 'phone' | 'lot') => {
    if (!query.trim()) {
      dispatch(setCustomers([]));
      return;
    }
  
    dispatch(setLoading(true));
    dispatch(setError(null));
    dispatch(setSearchQuery(query));
  
    try {
      const results = await searchCustomers(type, query);
      const adaptedCustomers = results.map(adaptCustomer);
      
      const customersWithWaiverStatus = await Promise.all(
        adaptedCustomers.map(async (customer: Customer) => {
          try {
            const hasSignedWaiver = await checkWaiverStatus(customer.id);
            return { ...customer, hasSignedWaiver };
          } catch (error) {
            console.error(`Failed to check waiver status for customer ${customer.id}:`, error);
            return customer;
          }
        })
      );
      dispatch(setCustomers(customersWithWaiverStatus));
    } catch (err) {
      dispatch(setError('Unable to search customers. Please try again.'));
      dispatch(setCustomers([]));
    } finally {
      dispatch(setLoading(false));
    }
  };

  const handleCheckIn = async () => {
    console.log('handleCheckIn called with:', { selectedCustomer, guestCount });
    if (selectedCustomer && guestCount > 0) {
      try {
        console.log('Attempting to log check-in with:', {
          id: selectedCustomer.id,
          guestCount,
          firstName: selectedCustomer.firstName,
          lastName: selectedCustomer.lastName,
          lotNumber: selectedCustomer.lotNumber
        });
        
        // Log the check-in with customer information
        await logCheckIn(
          selectedCustomer.id, 
          guestCount, 
          selectedCustomer.firstName, 
          selectedCustomer.lastName, 
          selectedCustomer.lotNumber
        );
        
        console.log('Check-in logged successfully');
        
        // Show confirmation
        dispatch(setShowConfirmation(true));
      } catch (error) {
        console.error('Failed to log check-in:', error);
        // Still show confirmation even if logging fails
        dispatch(setShowConfirmation(true));
      }
    } else {
      console.log('Invalid check-in attempt:', { selectedCustomer, guestCount });
      dispatch(setShowConfirmation(true));
    }
  };

  const handleWaiverResponse = (accepted: boolean) => {
    if (accepted) {
      // Don't automatically show confirmation dialog
      // dispatch(setShowConfirmation(true));
    } else {
      dispatch(resetState());
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-primary text-white py-6 px-4 shadow-lg">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-bold">Big Trees Village Rec Center Check In</h1>
          <p className="mt-2 text-primary/20">Please check in using your phone number, email, or lot number</p>
          {USE_MOCK_API && (
            <div className="mt-1 px-2 py-1 bg-yellow-500 text-white text-xs inline-block rounded">
              Demo Mode: Using Mock Data
            </div>
          )}
        </div>
      </header>

      <main className="max-w-3xl mx-auto p-4 mt-6">
        {showConfirmation ? (
          <div className="bg-green-50 rounded-lg p-8 text-center">
            <div 
            data-testid="green-checkmark"
            className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <Check className="h-8 w-8 text-green-600" />
            </div>
            <h2 className="text-2xl font-bold text-green-900 mb-2">All Set!</h2>
            <p className="text-green-700">You're checked in and ready to go. Enjoy your visit!</p>
          </div>
        ) : selectedCustomer ? (
          <CustomerDetail
            customer={selectedCustomer}
            guestCount={guestCount}
            showWaiver={selectedCustomer ? !selectedCustomer.hasSignedWaiver : false}
            onGuestCountChange={(count) => dispatch(setGuestCount(count))}
            onCheckIn={handleCheckIn}
            onWaiverResponse={handleWaiverResponse}
            onShowWaiver={() => dispatch(setShowWaiver(true))}
            onReset={resetState}
          />
        ) : (
          <>
            <SearchBar onSearch={handleSearch} isLoading={isLoading} />
            <div className="bg-white rounded-lg shadow-md">
              <CustomerList
                customers={customers}
                onSelectCustomer={(customer) => dispatch(setSelectedCustomer(customer))}
                isLoading={isLoading}
                error={error}
                searchQuery={searchQuery}
              />
            </div>
          </>
        )}
      </main>
    </div>
  );
}

export default App;

// src/App.svelte
<script lang="ts">
  import { Check, AlertCircle } from 'lucide-svelte';
  import type { Customer } from './types';
  import { unifiedSearch, validateQRCode, logCheckIn } from './api';
  import UnifiedSearch, { type UnifiedSearchResult } from './UnifiedSearch.svelte';
  import CustomerList from './CustomerList.svelte';
  import CustomerDetail from './CustomerDetail.svelte';
  import { resetState } from './stores/appStore';

  const STANDARD_ERROR_MESSAGE = 'An issue with check-in, please see the manager on duty';

  let customers: Customer[] = [];
  let isLoading = false;
  let error: string | null = null;
  let selectedCustomer: Customer | null = null;
  let guestCount = 1;
  let showConfirmation = false;
  let qrOrderId: string | null = null;

  const USE_MOCK_API = import.meta.env.VITE_USE_MOCK_API === 'true';

  import { onMount } from 'svelte';
  
  // Auto-dismiss confirmation after 3 seconds
  $: if (showConfirmation) {
    setTimeout(() => {
      handleResetState();
    }, 3000);
  }

  function handleResetState() {
    customers = [];
    selectedCustomer = null;
    error = null;
    showConfirmation = false;
    qrOrderId = null;
    guestCount = 1;
    resetState();
  }

  // Handle unified search results
  async function handleSearchResult(result: UnifiedSearchResult) {
    isLoading = false;
    error = null;

    if (result.type === 'qr') {
      // QR code result
      if (result.valid && result.customerId) {
        // Valid QR code - proceed to check-in
        qrOrderId = result.orderId || null;
        // For QR code check-in, we'll handle it directly
        await handleQRCheckIn(result.orderId!, result.customerId, guestCount);
      } else {
        // Invalid QR code
        error = result.reason || STANDARD_ERROR_MESSAGE;
        customers = [];
      }
    } else {
      // Search results
      if (result.results && result.results.length > 0) {
        // Adapt API results to Customer type
        const adaptedCustomers = result.results.map((c: any) => ({
          id: c.id,
          firstName: c.given_name || c.firstName || '',
          lastName: c.family_name || c.lastName || '',
          email: c.email_address || c.email || '',
          phone: c.phone_number || c.phone || '',
          lotNumber: c.reference_id || c.lotNumber,
          membershipType: c.membershipType || 'Non-Member',
          hasSignedWaiver: c.hasSignedWaiver || false,
        }));
        customers = adaptedCustomers;
      } else {
        customers = [];
        error = 'No customers found. Please try a different search.';
      }
    }
  }

  // Handle QR code scan
  async function handleQRCodeScanned(orderId: string) {
    isLoading = true;
    error = null;

    try {
      const validation = await validateQRCode(orderId);
      if (validation.valid && validation.customerId) {
        await handleQRCheckIn(orderId, validation.customerId, guestCount);
      } else {
        error = validation.reason || STANDARD_ERROR_MESSAGE;
      }
    } catch (err) {
      console.error('Error processing QR code:', err);
      error = STANDARD_ERROR_MESSAGE;
    } finally {
      isLoading = false;
    }
  }

  // Handle QR code check-in
  async function handleQRCheckIn(orderId: string, customerId: string, guests: number) {
    try {
      const result = await logCheckIn(
        customerId,
        guests,
        '', // firstName - not needed for QR check-in
        '', // lastName - not needed for QR check-in
        undefined, // lotNumber
        orderId
      );

      if (result.success) {
        showConfirmation = true;
        if (result.queued) {
          // Check-in was queued (offline mode)
          console.log('Check-in queued for sync:', result.message);
        }
      } else {
        error = result.message || STANDARD_ERROR_MESSAGE;
      }
    } catch (err) {
      console.error('Error during QR check-in:', err);
      error = STANDARD_ERROR_MESSAGE;
    }
  }

  // Handle manual check-in
  async function handleCheckIn() {
    if (!selectedCustomer || guestCount < 1) {
      error = 'Please select a customer and enter guest count';
      return;
    }

    isLoading = true;
    error = null;

    try {
      const result = await logCheckIn(
        selectedCustomer.id,
        guestCount,
        selectedCustomer.firstName,
        selectedCustomer.lastName,
        selectedCustomer.lotNumber
      );

      if (result.success) {
        showConfirmation = true;
      } else {
        error = result.message || STANDARD_ERROR_MESSAGE;
      }
    } catch (err) {
      console.error('Error during check-in:', err);
      error = STANDARD_ERROR_MESSAGE;
    } finally {
      isLoading = false;
    }
  }

  // Handle search start
  function handleSearchStart() {
    isLoading = true;
    error = null;
  }
</script>

<div class="min-h-screen bg-gray-50">
  <header class="bg-primary-600 text-white py-6 px-4 shadow-lg">
    <div class="max-w-3xl mx-auto">
      <h1 class="text-3xl font-bold">Big Trees Village Rec Center Check In</h1>
      <p class="mt-2 text-primary-100">
        Scan your QR code or search by name, phone, email, address, or lot number
      </p>
      {#if USE_MOCK_API}
        <div class="mt-1 px-2 py-1 bg-yellow-500 text-white text-xs inline-block rounded">
          Demo Mode: Using Mock Data
        </div>
      {/if}
    </div>
  </header>

  <main class="max-w-3xl mx-auto p-4 mt-6">
    {#if showConfirmation}
      <div class="bg-green-50 rounded-lg p-8 text-center">
        <div 
          data-testid="green-checkmark"
          class="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4"
        >
          <Check class="h-8 w-8 text-green-600" />
        </div>
        <h2 class="text-2xl font-bold text-green-900 mb-2">All Set!</h2>
        <p class="text-green-700">You're checked in and ready to go. Enjoy your visit!</p>
      </div>
    {:else if selectedCustomer}
      <CustomerDetail
        customer={selectedCustomer}
        {guestCount}
        showWaiver={!selectedCustomer.hasSignedWaiver}
        onGuestCountChange={(count) => guestCount = count}
        onCheckIn={handleCheckIn}
        onWaiverResponse={(accepted) => {
          if (!accepted) {
            handleResetState();
          }
        }}
        onShowWaiver={() => {}}
        onReset={handleResetState}
      />
    {:else}
      <UnifiedSearch
        onSearchResult={handleSearchResult}
        onQRCodeScanned={handleQRCodeScanned}
        onSearchStart={handleSearchStart}
        {isLoading}
        error={null}
      />
      
      {#if error}
        <div class="bg-red-50 border border-red-200 rounded-lg p-4 mb-6 flex items-center gap-3">
          <AlertCircle class="h-5 w-5 text-red-600 flex-shrink-0" />
          <p class="text-red-700">{error}</p>
        </div>
      {/if}

      {#if customers.length > 0}
        <div class="bg-white rounded-lg shadow-md">
          <CustomerList
            {customers}
            onSelectCustomer={(customer) => selectedCustomer = customer}
            {isLoading}
            error={null}
            searchQuery=""
          />
        </div>
      {/if}
    {/if}
  </main>
</div>
