// apps/web/src/lib/components/CustomerDetail.svelte
<script lang="ts">
	import { X, Users } from 'lucide-svelte';
	import type { SearchResult } from '../types';

	export let customer: SearchResult;
	export let guestCount: number;
	export let onGuestCountChange: (count: number) => void;
	export let onCheckIn: () => void;
	export let onReset: () => void;

	let hasSelected = guestCount > 0;

	// Update hasSelected when guestCount changes
	$: hasSelected = guestCount > 0;

	function handleGuestCountClick(count: number) {
		onGuestCountChange(count);
		hasSelected = true;
	}

	// Extract first name from displayName
	$: firstName = customer?.displayName?.split(' ')[0] || 'Guest';
</script>

<div class="bg-white rounded-lg shadow-md p-6">
	<div class="flex justify-between items-start mb-6">
		<div>
			<h2 class="text-2xl font-bold text-gray-900">
				Hi, {firstName}
			</h2>
		</div>
		<button
			on:click={() => {
				onReset();
			}}
			class="p-2 text-gray-500 hover:text-gray-700"
			data-testid="close-details"
		>
			<X class="h-5 w-5" />
		</button>
	</div>

	<div class="max-w-2xl mx-auto">
		<div class="bg-gray-50 p-6 rounded-lg">
			<h3 class="text-lg font-medium text-gray-900 mb-4">Check In</h3>
			<div class="mb-4">
				<label class="block text-sm font-medium text-gray-700 mb-4">
					Number of guests (including you)
				</label>
				<div class="flex flex-col items-center mb-6">
					<div class="text-7xl font-bold text-primary-600 mb-2">
						{hasSelected ? guestCount : '-'}
					</div>
					<div class="text-sm text-gray-500 mb-4">Total Guests</div>
				</div>
				<button
					data-testid="checkin-button"
					on:click={onCheckIn}
					disabled={!hasSelected}
					class="w-full py-3 rounded-lg flex items-center justify-center gap-2 mb-6 {hasSelected
						? 'bg-primary-600 text-white hover:bg-primary-700' 
						: 'bg-gray-300 text-gray-500 cursor-not-allowed'}"
				>
					<Users class="h-5 w-5" />
					<span>
						{!hasSelected 
							? 'Please Select Number of Guests' 
							: 'Check In Now'}
					</span>
				</button>
				
				<!-- Guest count buttons grid -->
				<div class="grid grid-cols-2 sm:grid-cols-5 gap-3">
					{#each Array(10) as _, i}
						{@const count = i + 1}
						<button
							data-testid="guest-count-button-{count}"
							on:click={() => handleGuestCountClick(count)}
							class="py-4 px-4 rounded-lg text-lg font-semibold transition-colors {guestCount === count
								? 'bg-primary-600 text-white hover:bg-primary-700'
								: 'bg-white text-gray-700 border-2 border-gray-300 hover:border-primary-500 hover:bg-primary-50'}"
						>
							{count}
						</button>
					{/each}
				</div>
			</div>
		</div>
	</div>
</div>

// src/CustomerDetail.tsx
import React from 'react';
import { X, Users, FileText } from 'lucide-react';
import { Customer } from './types';
import { signWaiver } from './api';

type CustomerDetailProps = {
  customer: Customer;
  guestCount: number;
  showWaiver: boolean;
  onGuestCountChange: (count: number) => void;
  onCheckIn: () => void;
  onWaiverResponse: (accepted: boolean) => void;
  onShowWaiver: () => void;
  onReset: () => void;
};

export const CustomerDetail = ({
  customer,
  guestCount,
  showWaiver,
  onGuestCountChange,
  onCheckIn,
  onWaiverResponse,
  onShowWaiver,
  onReset
}: CustomerDetailProps) => {
  // TODO - Replace with actual waiver text
  const WAIVER_TEXT = `RELEASE AND WAIVER OF LIABILITY IPSEM LOREM...`; 

  return (
    <div className="bg-white rounded-lg shadow-md p-6">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-xl font-semibold text-gray-900">
          Welcome, {customer.firstName}!
        </h2>
        <button
          onClick={onReset}
          className="p-2 text-gray-400 hover:text-gray-600"
        >
          <X className="h-6 w-6" />
        </button>
      </div>
      
      <div className="grid md:grid-cols-2 gap-6">
        <div className="bg-gray-50 p-6 rounded-lg">
          <h3 className="text-lg font-medium text-gray-900 mb-4">Check In</h3>
          <div className="mb-4">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Number of guests (including you)
            </label>
            <input
              data-testid="checkin-input"
              type="number"
              min="1"
              max="10"
              value={guestCount}
              onChange={(e) => onGuestCountChange(Math.max(1, parseInt(e.target.value) || 1))}
              className="w-full px-3 py-2 border border-gray-300 rounded-md"
            />
          </div>
          <button
            data-testid="checkin-button"
            onClick={onCheckIn}
            disabled={showWaiver}
            className={`w-full py-3 rounded-lg flex items-center justify-center gap-2 ${
              !showWaiver 
                ? 'bg-blue-600 text-white hover:bg-blue-700' 
                : 'bg-gray-300 text-gray-500 cursor-not-allowed'
            }`}
          >
            <Users className="h-5 w-5" />
            <span>{showWaiver ? 'Please Sign Waiver First' : 'Check In Now'}</span>
          </button>
          {showWaiver && (
            <p className="mt-2 text-sm text-red-600">
              You must sign the waiver before checking in
            </p>
          )}
        </div>

        <div className="bg-gray-50 p-6 rounded-lg">
          {showWaiver ? (
            <div>
              <h3 className="text-lg font-medium text-gray-900 mb-4">Liability Waiver</h3>
              <div className="bg-white p-4 rounded-md mb-4 h-48 overflow-y-auto text-sm text-gray-600">
                {WAIVER_TEXT}
              </div>
              <div className="flex gap-3">
                <button
                  onClick={() => {
                    signWaiver(customer.id);
                    onWaiverResponse(true);
                  }}
                  className="flex-1 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700"
                >
                  Accept
                </button>
                <button
                  onClick={() => onWaiverResponse(false)}
                  className="flex-1 py-3 bg-red-600 text-white rounded-lg hover:bg-red-700"
                >
                  Decline
                </button>
              </div>
            </div>
          ) : (
            <div>
              <h3 
                data-testid="signwaiver-text"
                className="text-lg font-medium text-gray-900 mb-4"
              >
                Waiver Already Signed
              </h3>
              <p className="text-sm text-gray-600 mb-4">
                You have previously signed the liability waiver, Thank You!
              </p>
              {/* <button
                data-testid="signwaiver-button"
                onClick={onShowWaiver}
                className="w-full py-3 bg-gray-600 text-white rounded-lg hover:bg-gray-700 flex items-center justify-center gap-2"
              >
                <FileText className="h-5 w-5" />
                <span>View Waiver</span>
              </button> */}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
