// src/CustomerDetail.tsx
import React, { useEffect, useRef, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { X, Users, FileText, Settings } from 'lucide-react';
import { RootState } from './App'; // Assuming RootState is exported from App.tsx
import { Customer } from './types';
import { signWaiver } from './api';
import { WAIVER_TEXT } from './constants';
import { AdminView } from './AdminView';

// Action creators
const setGuestCount = (count: number) => ({ type: 'SET_GUEST_COUNT', payload: count });
const setShowConfirmation = (show: boolean) => ({ type: 'SET_SHOW_CONFIRMATION', payload: show });
const setShowWaiver = (show: boolean) => ({ type: 'SET_SHOW_WAIVER', payload: show });
const updateCustomerWaiverStatus = (customerId: string, hasSignedWaiver: boolean) => ({
  type: 'UPDATE_CUSTOMER_WAIVER_STATUS',
  payload: { customerId, hasSignedWaiver }
});
const resetState = () => ({ type: 'RESET_STATE' });

type CustomerDetailProps = {
  customer: Customer;
  guestCount: number;
  showWaiver: boolean;
  onGuestCountChange: (count: number) => void;
  onCheckIn: () => void;
  onWaiverResponse: (accepted: boolean) => void;
  onShowWaiver: () => void;
  onReset: () => void;
};

export const CustomerDetail = ({
  customer,
  guestCount,
  showWaiver,
  onGuestCountChange,
  onCheckIn,
  onWaiverResponse,
  onShowWaiver,
  onReset,
}: CustomerDetailProps) => {
  const dispatch = useDispatch();
  const guestCountInputRef = useRef<HTMLInputElement>(null);
  const [isOtherSelected, setIsOtherSelected] = useState(false);
  const [customGuestCount, setCustomGuestCount] = useState('');
  const [hasSelected, setHasSelected] = useState(false);
  const [showAdmin, setShowAdmin] = useState(false);

  // Initialize hasSelected based on guestCount
  useEffect(() => {
    setHasSelected(guestCount > 0);
  }, [guestCount]);

  return (
    <div className="bg-white rounded-lg shadow-md p-6">
      <div className="flex justify-between items-start mb-6">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">
            Hi, {customer.firstName}
          </h2>
        </div>
        <div className="flex space-x-2">
          <button
            onClick={() => setShowAdmin(true)}
            className="p-2 text-gray-500 hover:text-gray-700"
            title="Admin View"
          >
            <Settings className="h-5 w-5" />
          </button>
          <button
            onClick={() => {
              dispatch(resetState());
              onReset();
            }}
            className="p-2 text-gray-500 hover:text-gray-700"
            data-testid="close-details"
          >
            <X className="h-5 w-5" />
          </button>
        </div>
      </div>

      {showAdmin && (
        <AdminView
          customer={customer}
          onClose={() => setShowAdmin(false)}
        />
      )}

      <div className="grid md:grid-cols-2 gap-6">
        <div className="bg-gray-50 p-6 rounded-lg">
          <h3 className="text-lg font-medium text-gray-900 mb-4">Check In</h3>
          <div className="mb-4">
            <label className="block text-sm font-medium text-gray-700 mb-4">
              Number of guests (including you)
            </label>
            <div className="flex flex-col items-center mb-6">
              <div className="text-7xl font-bold text-primary mb-2">
                {hasSelected ? guestCount : '-'}
              </div>
              <div className="text-sm text-gray-500 mb-4">Total Guests</div>
            </div>
            <button
              data-testid="checkin-button"
              onClick={() => onCheckIn()}
              disabled={showWaiver || !hasSelected}
              className={`w-full py-3 rounded-lg flex items-center justify-center gap-2 mb-6 ${
                !showWaiver && hasSelected
                  ? 'bg-primary text-white hover:bg-primary/90' 
                  : 'bg-gray-300 text-gray-500 cursor-not-allowed'
              }`}
            >
              <Users className="h-5 w-5" />
              <span>
                {showWaiver 
                  ? 'Please Sign Waiver First' 
                  : !hasSelected 
                    ? 'Please Select Number of Guests' 
                    : 'Check In Now'}
              </span>
            </button>
            {showWaiver && (
              <p 
                data-testid="nowaiver-cant-checkin" 
                className="mt-2 text-sm text-red-600 mb-6"
              >
                You must sign the waiver before checking in
              </p>
            )}
            <div className="relative w-full mb-4">
              <select
                data-testid="guest-count-select"
                value={isOtherSelected ? 'other' : (hasSelected ? guestCount.toString() : '')}
                onChange={(e) => {
                  const value = e.target.value;
                  if (value === 'other') {
                    setIsOtherSelected(true);
                    setCustomGuestCount('');
                    setHasSelected(false);
                  } else {
                    setIsOtherSelected(false);
                    const numValue = parseInt(value);
                    dispatch(setGuestCount(numValue));
                    setHasSelected(true);
                  }
                }}
                className="w-full px-3 py-2 border border-gray-300 rounded-md text-center text-lg appearance-none bg-white"
              >
                <option value="" disabled selected>Select number of guests</option>
                <option value="1">1 Guest</option>
                <option value="2">2 Guests</option>
                <option value="3">3 Guests</option>
                <option value="4">4 Guests</option>
                <option value="5">5 Guests</option>
                <option value="6">6 Guests</option>
                <option value="7">7 Guests</option>
                <option value="8">8 Guests</option>
                <option value="9">9 Guests</option>
                <option value="10">10 Guests</option>
                <option value="other">Other</option>
              </select>
              <div className="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none">
                <svg className="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd" />
                </svg>
              </div>
            </div>
            {isOtherSelected && (
              <div className="relative w-full">
                <input
                  data-testid="checkin-input"
                  ref={guestCountInputRef}
                  type="number"
                  min="1"
                  value={customGuestCount}
                  onChange={(e) => {
                    const value = e.target.value;
                    setCustomGuestCount(value);
                    if (value) {
                      const numValue = parseInt(value);
                      if (!isNaN(numValue) && numValue >= 1) {
                        dispatch(setGuestCount(numValue));
                        setHasSelected(true);
                      } else {
                        setHasSelected(false);
                      }
                    } else {
                      setHasSelected(false);
                    }
                  }}
                  onBlur={(e) => {
                    // Ensure the value is valid when focus is lost
                    const value = e.target.value;
                    if (value) {
                      const numValue = parseInt(value);
                      if (isNaN(numValue) || numValue < 1) {
                        setCustomGuestCount('');
                        setHasSelected(false);
                      }
                    } else {
                      setCustomGuestCount('');
                      setHasSelected(false);
                    }
                  }}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md text-center text-lg"
                  placeholder="Enter number of guests"
                />
              </div>
            )}
          </div>
        </div>

        <div className="bg-gray-50 p-6 rounded-lg">
          {showWaiver ? (
            <div>
              <h3 className="text-lg font-medium text-gray-900 mb-4">Liability Waiver</h3>
              <div className="flex flex-col items-center p-4">
                <img 
                  src="/assets/waiver-qr-code.png" 
                  alt="Waiver QR Code" 
                  className="w-48 h-48"
                  data-testid="waiver-qr-code"
                />
                <p className="mt-4 text-sm text-gray-600">
                  Scan this QR code to sign the waiver
                </p>
              </div>
              <div className="flex gap-3">
                <button
                  data-testid="accept-waiver-button"
                  onClick={async () => {
                    const success = await signWaiver(customer.id);
                    if (success) {
                      dispatch(updateCustomerWaiverStatus(customer.id, true));
                      dispatch(setShowWaiver(false));
                      onWaiverResponse(true);
                      setTimeout(() => {
                        guestCountInputRef.current?.focus();
                      }, 100);
                    }
                  }}
                  className="flex-1 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700"
                >
                  I've already signed
                </button>
              </div>
            </div>
          ) : (
            <div>
              <h3 
                data-testid="signwaiver-text"
                className="text-lg font-medium text-gray-900 mb-4"
              >
                Waiver Already Signed
              </h3>
              <p className="text-sm text-gray-600 mb-4">
                You have previously signed the liability waiver, Thank You!
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

// src/CustomerDetail.svelte
<script lang="ts">
  import { X, Users, Settings } from 'lucide-svelte';
  import type { Customer } from './types';
  import { signWaiver } from './api';
  import { setGuestCount, setShowWaiver, updateCustomerWaiverStatus } from './stores/appStore';
  import AdminView from './AdminView.svelte';

  export let customer: Customer;
  export let guestCount: number;
  export let showWaiver: boolean;
  export let onGuestCountChange: (count: number) => void;
  export let onCheckIn: () => void;
  export let onWaiverResponse: (accepted: boolean) => void;
  export let onShowWaiver: () => void;
  export let onReset: () => void;
  
  let isOtherSelected = false;
  let customGuestCount = '';
  let hasSelected = guestCount > 0;
  let showAdmin = false;
  let guestCountInputElement: HTMLInputElement;

  // Update hasSelected when guestCount changes
  $: hasSelected = guestCount > 0;

  function handleSelectChange(e: Event) {
    const target = e.target as HTMLSelectElement;
    const value = target.value;
    if (value === 'other') {
      isOtherSelected = true;
      customGuestCount = '';
      hasSelected = false;
      onGuestCountChange(0);
    } else {
      isOtherSelected = false;
      const numValue = parseInt(value);
      setGuestCount(numValue);
      onGuestCountChange(numValue);
      hasSelected = true;
    }
  }

  function handleCustomInput(e: Event) {
    const target = e.target as HTMLInputElement;
    const value = target.value;
    customGuestCount = value;
    if (value) {
      const numValue = parseInt(value);
      if (!isNaN(numValue) && numValue >= 1) {
        setGuestCount(numValue);
        onGuestCountChange(numValue);
        hasSelected = true;
      } else {
        hasSelected = false;
      }
    } else {
      hasSelected = false;
    }
  }

  function handleCustomBlur() {
    if (customGuestCount) {
      const numValue = parseInt(customGuestCount);
      if (isNaN(numValue) || numValue < 1) {
        customGuestCount = '';
        hasSelected = false;
        onGuestCountChange(0);
      }
    } else {
      customGuestCount = '';
      hasSelected = false;
      onGuestCountChange(0);
    }
  }

  async function handleWaiverAccept() {
    const success = await signWaiver(customer.id);
    if (success) {
      updateCustomerWaiverStatus(customer.id, true);
      setShowWaiver(false);
      onWaiverResponse(true);
      setTimeout(() => {
        if (guestCountInputElement) {
          guestCountInputElement.focus();
        }
      }, 100);
    }
  }
</script>

<div class="bg-white rounded-lg shadow-md p-6">
  <div class="flex justify-between items-start mb-6">
    <div>
      <h2 class="text-2xl font-bold text-gray-900">
        Hi, {customer.firstName}
      </h2>
    </div>
    <div class="flex space-x-2">
      <button
        on:click={() => showAdmin = true}
        class="p-2 text-gray-500 hover:text-gray-700"
        title="Admin View"
      >
        <Settings class="h-5 w-5" />
      </button>
      <button
        on:click={() => {
          onReset();
        }}
        class="p-2 text-gray-500 hover:text-gray-700"
        data-testid="close-details"
      >
        <X class="h-5 w-5" />
      </button>
    </div>
  </div>

  {#if showAdmin}
    <AdminView
      {customer}
      onClose={() => showAdmin = false}
    />
  {/if}

  <div class="grid md:grid-cols-2 gap-6">
    <div class="bg-gray-50 p-6 rounded-lg">
      <h3 class="text-lg font-medium text-gray-900 mb-4">Check In</h3>
      <div class="mb-4">
        <label class="block text-sm font-medium text-gray-700 mb-4">
          Number of guests (including you)
        </label>
        <div class="flex flex-col items-center mb-6">
          <div class="text-7xl font-bold text-primary-600 mb-2">
            {hasSelected ? guestCount : '-'}
          </div>
          <div class="text-sm text-gray-500 mb-4">Total Guests</div>
        </div>
        <button
          data-testid="checkin-button"
          on:click={onCheckIn}
          disabled={showWaiver || !hasSelected}
          class="w-full py-3 rounded-lg flex items-center justify-center gap-2 mb-6 {!showWaiver && hasSelected
            ? 'bg-primary-600 text-white hover:bg-primary-700' 
            : 'bg-gray-300 text-gray-500 cursor-not-allowed'}"
        >
          <Users class="h-5 w-5" />
          <span>
            {showWaiver 
              ? 'Please Sign Waiver First' 
              : !hasSelected 
                ? 'Please Select Number of Guests' 
                : 'Check In Now'}
          </span>
        </button>
        {#if showWaiver}
          <p 
            data-testid="nowaiver-cant-checkin" 
            class="mt-2 text-sm text-red-600 mb-6"
          >
            You must sign the waiver before checking in
          </p>
        {/if}
        <div class="relative w-full mb-4">
          <select
            data-testid="guest-count-select"
            value={isOtherSelected ? 'other' : (hasSelected ? guestCount.toString() : '')}
            on:change={handleSelectChange}
            class="w-full px-3 py-2 border border-gray-300 rounded-md text-center text-lg appearance-none bg-white"
          >
            <option value="" disabled selected>Select number of guests</option>
            <option value="1">1 Guest</option>
            <option value="2">2 Guests</option>
            <option value="3">3 Guests</option>
            <option value="4">4 Guests</option>
            <option value="5">5 Guests</option>
            <option value="6">6 Guests</option>
            <option value="7">7 Guests</option>
            <option value="8">8 Guests</option>
            <option value="9">9 Guests</option>
            <option value="10">10 Guests</option>
            <option value="other">Other</option>
          </select>
          <div class="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none">
            <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
          </div>
        </div>
        {#if isOtherSelected}
          <div class="relative w-full">
            <input
              bind:this={guestCountInputElement}
              data-testid="checkin-input"
              type="number"
              min="1"
              bind:value={customGuestCount}
              on:input={handleCustomInput}
              on:blur={handleCustomBlur}
              class="w-full px-3 py-2 border border-gray-300 rounded-md text-center text-lg"
              placeholder="Enter number of guests"
            />
          </div>
        {/if}
      </div>
    </div>

    <div class="bg-gray-50 p-6 rounded-lg">
      {#if showWaiver}
        <div>
          <h3 class="text-lg font-medium text-gray-900 mb-4">Liability Waiver</h3>
          <div class="flex flex-col items-center p-4">
            <img 
              src="/assets/waiver-qr-code.png" 
              alt="Waiver QR Code" 
              class="w-48 h-48"
              data-testid="waiver-qr-code"
            />
            <p class="mt-4 text-sm text-gray-600">
              Scan this QR code to sign the waiver
            </p>
          </div>
          <div class="flex gap-3">
            <button
              data-testid="accept-waiver-button"
              on:click={handleWaiverAccept}
              class="flex-1 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700"
            >
              I've already signed
            </button>
          </div>
        </div>
      {:else}
        <div>
          <h3 
            data-testid="signwaiver-text"
            class="text-lg font-medium text-gray-900 mb-4"
          >
            Waiver Already Signed
          </h3>
          <p class="text-sm text-gray-600 mb-4">
            You have previously signed the liability waiver, Thank You!
          </p>
        </div>
      {/if}
    </div>
  </div>
</div>
